name: build-ci

on: [pull_request, push]

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: esp-idf setup
        run: bash ./.github/ci/idf-setup.sh
      - uses: actions/upload-artifact@v3
        with:
          name: esp-idf
          path: esp-idf
      - uses: actions/upload-artifact@v3  
        with:
          name: project
          path: .

  build:
    runs-on: ubuntu-latest
    needs: checkout
    strategy:
      matrix:
        platform: [ESP32S3_FREENOVE, ESP32S3_HMI43V3, ZX3D50CE02S-SRC-4832, ESP32S3_8048S070C]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: esp-idf
          path: esp-idf
      - uses: actions/download-artifact@v3
        with:
          name: project
          path: .  
      - name: build ${{ matrix.platform }}
        run: bash ./.github/ci/${{ matrix.platform }}.sh
        continue-on-error: true
      - name: mark ${{ matrix.platform }} error
        if: failure()
        run: echo "BUILD_ERROR=1" >> $GITHUB_ENV
        
  finalize:
    runs-on: ubuntu-latest 
    needs: build
    if: always()
    steps:
      - name: Final check
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |  
          if [ "${{ env.BUILD_ERROR }}" -ne "0" ]; then
            bash ./.github/ci/final-check.sh "$GITHUB_RUN_ID" "failure"
          else  
            bash ./.github/ci/final-check.sh "$GITHUB_RUN_ID" "success"
          fi


